.TH SMC 1 "Oct, 2015"
.SH NAME
smc \- Apple System Management Control (SMC) Tool
.SH SYNOPSIS
.B smc [options]
.SH DESCRIPTION
.B smc
Command line interface to Apple System Management Control
.SH OPTIONS
.TP
.B \-f
fan info decoded
.TP
.B \-h
help
.TP
.B \-k <key>
key to manipulate
.TP
.B \-l
list all keys and values
.TP
.B \-r
read the value of a key
.TP
.B \-w <value>
write the specified value to a key
.TP
.B \-v
version
.SH HOMEPAGE
.PP
.B Repository:
https://github.com/yoshida-mediba/smc
